# Generated by Django 5.1.4 on 2025-01-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bestseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSeller',
        ),
    ]
