# Generated by Django 5.1.4 on 2025-01-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_bestseller_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='price',
        ),
    ]
