# Generated by Django 5.1.4 on 2025-01-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_bestseller_image_remove_bestseller_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='testimonials/')),
            ],
        ),
    ]
