# Generated by Django 5.1.4 on 2025-01-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
