# Generated by Django 5.1.4 on 2025-02-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
